import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileText, Download, IndianRupee, Share2 } from "lucide-react";

interface QuotationItem {
  name: string;
  specifications: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

interface QuotationGeneratorProps {
  items: QuotationItem[];
  customerName?: string;
  gstRate?: number;
  deliveryCharge?: number;
}

const QuotationGenerator = ({ items, customerName, gstRate = 18, deliveryCharge = 0 }: QuotationGeneratorProps) => {
  const [showQuotation, setShowQuotation] = useState(false);

  const subtotal = items.reduce((sum, item) => sum + item.total, 0);
  const gstAmount = (subtotal * gstRate) / 100;
  const grandTotal = subtotal + gstAmount + deliveryCharge;
  const quotationNumber = `PF-${Date.now().toString(36).toUpperCase()}`;
  const validUntil = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString("en-IN");

  const generatePDF = () => {
    // Create printable quotation HTML
    const html = `
<!DOCTYPE html>
<html><head><title>Quotation ${quotationNumber}</title>
<style>
  body { font-family: 'Segoe UI', sans-serif; margin: 0; padding: 40px; color: #1a1a2e; }
  .header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 30px; }
  .logo { font-size: 24px; font-weight: 700; color: #e8553a; }
  .logo span { color: #1a1a2e; }
  .qno { font-size: 12px; color: #666; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #1a1a2e; color: #fff; padding: 10px; text-align: left; font-size: 13px; }
  td { padding: 10px; border-bottom: 1px solid #eee; font-size: 13px; }
  .right { text-align: right; }
  .total-row td { font-weight: 700; border-top: 2px solid #1a1a2e; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 11px; color: #999; }
  .badge { display: inline-block; background: #e8553a; color: #fff; padding: 2px 8px; border-radius: 4px; font-size: 11px; }
</style></head><body>
<div class="header">
  <div><div class="logo">Print<span>Flow</span></div><div class="qno">Quotation #${quotationNumber}</div></div>
  <div style="text-align:right"><div class="badge">QUOTATION</div><div class="qno">Date: ${new Date().toLocaleDateString("en-IN")}<br/>Valid Until: ${validUntil}</div></div>
</div>
${customerName ? `<p><strong>To:</strong> ${customerName}</p>` : ""}
<table>
  <thead><tr><th>#</th><th>Product</th><th>Specifications</th><th class="right">Qty</th><th class="right">Unit Price</th><th class="right">Total</th></tr></thead>
  <tbody>
    ${items.map((item, i) => `<tr><td>${i + 1}</td><td>${item.name}</td><td>${item.specifications}</td><td class="right">${item.quantity.toLocaleString("en-IN")}</td><td class="right">₹${item.unitPrice.toFixed(2)}</td><td class="right">₹${item.total.toLocaleString("en-IN")}</td></tr>`).join("")}
  </tbody>
</table>
<table style="width:300px;margin-left:auto">
  <tr><td>Subtotal</td><td class="right">₹${subtotal.toLocaleString("en-IN")}</td></tr>
  <tr><td>GST (${gstRate}%)</td><td class="right">₹${gstAmount.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</td></tr>
  ${deliveryCharge > 0 ? `<tr><td>Delivery</td><td class="right">₹${deliveryCharge.toLocaleString("en-IN")}</td></tr>` : ""}
  <tr class="total-row"><td>Grand Total</td><td class="right">₹${grandTotal.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</td></tr>
</table>
<div class="footer">
  <p><strong>Terms & Conditions:</strong></p>
  <ul>
    <li>This quotation is valid for 7 days from the date of issue.</li>
    <li>50% advance payment required to start production.</li>
    <li>GST @ ${gstRate}% applicable as per government norms.</li>
    <li>Delivery timeline starts after design approval and payment confirmation.</li>
  </ul>
  <p style="margin-top:20px">Generated by PrintFlow • India's #1 Print Ordering Platform</p>
</div>
</body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      win.onload = () => win.print();
    }
  };

  if (!showQuotation) {
    return (
      <Button variant="outline" className="gap-2" onClick={() => setShowQuotation(true)}>
        <FileText className="w-4 h-4" /> View Quotation
      </Button>
    );
  }

  return (
    <div className="bg-card rounded-xl border border-border p-5 shadow-card">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-accent" />
          <h3 className="font-display font-semibold text-foreground">Quotation</h3>
        </div>
        <span className="text-xs bg-accent/10 text-accent px-2 py-1 rounded-full font-medium">
          #{quotationNumber}
        </span>
      </div>

      {/* Items */}
      <div className="space-y-3 mb-4">
        {items.map((item, i) => (
          <div key={i} className="flex justify-between items-start py-2 border-b border-border last:border-0">
            <div>
              <p className="text-sm font-medium text-foreground">{item.name}</p>
              <p className="text-xs text-muted-foreground">{item.specifications}</p>
              <p className="text-xs text-muted-foreground">Qty: {item.quantity.toLocaleString("en-IN")}</p>
            </div>
            <p className="text-sm font-semibold text-foreground">₹{item.total.toLocaleString("en-IN")}</p>
          </div>
        ))}
      </div>

      {/* Totals */}
      <div className="space-y-2 border-t border-border pt-3">
        <div className="flex justify-between text-sm">
          <span className="text-muted-foreground">Subtotal</span>
          <span className="text-foreground">₹{subtotal.toLocaleString("en-IN")}</span>
        </div>
        <div className="flex justify-between text-sm">
          <span className="text-muted-foreground">GST ({gstRate}%)</span>
          <span className="text-foreground">₹{gstAmount.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</span>
        </div>
        {deliveryCharge > 0 && (
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">Delivery</span>
            <span className="text-foreground">₹{deliveryCharge.toLocaleString("en-IN")}</span>
          </div>
        )}
        <div className="flex justify-between text-base font-bold pt-2 border-t border-border">
          <span className="text-foreground">Grand Total</span>
          <span className="text-accent flex items-center gap-1">
            <IndianRupee className="w-4 h-4" />
            {grandTotal.toLocaleString("en-IN", { maximumFractionDigits: 0 })}
          </span>
        </div>
      </div>

      <p className="text-xs text-muted-foreground mt-3">Valid until {validUntil} • GST as per govt. norms</p>

      <div className="flex gap-2 mt-4">
        <Button variant="coral" className="flex-1 gap-2" onClick={generatePDF}>
          <Download className="w-4 h-4" /> Download PDF
        </Button>
        <Button variant="outline" className="gap-2">
          <Share2 className="w-4 h-4" /> Share
        </Button>
      </div>
    </div>
  );
};

export default QuotationGenerator;
